/* tslint:disable */

/**
 * Binance Public Spot WebSocket Streams
 *
 * OpenAPI Specifications for the Binance Public Spot WebSocket Streams
 *
 * API documents:
 * - [Github web-socket-streams documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md)
 * - [General API information for web-socket-streams on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams)
 *
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AllTickerResponseInner
 */
export interface AllTickerResponseInner {
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    e?: string;
    /**
     *
     * @type {number}
     * @memberof AllTickerResponseInner
     */
    E?: number;
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    s?: string;
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    p?: string;
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    P?: string;
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    w?: string;
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    x?: string;
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    c?: string;
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    Q?: string;
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    b?: string;
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    B?: string;
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    a?: string;
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    A?: string;
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    o?: string;
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    h?: string;
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    l?: string;
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    v?: string;
    /**
     *
     * @type {string}
     * @memberof AllTickerResponseInner
     */
    q?: string;
    /**
     *
     * @type {number}
     * @memberof AllTickerResponseInner
     */
    O?: number;
    /**
     *
     * @type {number}
     * @memberof AllTickerResponseInner
     */
    C?: number;
    /**
     *
     * @type {number}
     * @memberof AllTickerResponseInner
     */
    F?: number;
    /**
     *
     * @type {number}
     * @memberof AllTickerResponseInner
     */
    L?: number;
    /**
     *
     * @type {number}
     * @memberof AllTickerResponseInner
     */
    n?: number;
}
