/* tslint:disable */

/**
 * Binance Public Derivatives Trading COIN Futures WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Public Derivatives Trading COIN Futures WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface IndexKlineCandlestickStreamsResponseK
 */
export interface IndexKlineCandlestickStreamsResponseK {
    /**
     *
     * @type {number}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    t?: number;
    /**
     *
     * @type {number}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    T?: number;
    /**
     *
     * @type {string}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    s?: string;
    /**
     *
     * @type {string}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    i?: string;
    /**
     *
     * @type {number}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    f?: number;
    /**
     *
     * @type {number}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    L?: number;
    /**
     *
     * @type {string}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    o?: string;
    /**
     *
     * @type {string}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    c?: string;
    /**
     *
     * @type {string}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    h?: string;
    /**
     *
     * @type {string}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    l?: string;
    /**
     *
     * @type {string}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    v?: string;
    /**
     *
     * @type {number}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    n?: number;
    /**
     *
     * @type {boolean}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    x?: boolean;
    /**
     *
     * @type {string}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    q?: string;
    /**
     *
     * @type {string}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    V?: string;
    /**
     *
     * @type {string}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    Q?: string;
    /**
     *
     * @type {string}
     * @memberof IndexKlineCandlestickStreamsResponseK
     */
    B?: string;
}
