/* tslint:disable */
/* eslint-disable */

/**
 * Binance Derivatives Trading USDS Futures REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading USDS Futures REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PositionInformationV3Response1Inner } from './position-information-v3-response1-inner';

/**
 *
 * @export
 * @interface PositionInformationV3Response1
 */
export interface PositionInformationV3Response1
    extends Array<PositionInformationV3Response1Inner> {}
