/* tslint:disable */

/**
 * Binance Public Derivatives Trading Portfolio Margin REST API
 *
 * OpenAPI Specification for the Binance Public Derivatives Trading Portfolio Margin REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MarginAccountTradeListResponseInner
 */
export interface MarginAccountTradeListResponseInner {
    /**
     *
     * @type {string}
     * @memberof MarginAccountTradeListResponseInner
     */
    commission?: string;
    /**
     *
     * @type {string}
     * @memberof MarginAccountTradeListResponseInner
     */
    commissionAsset?: string;
    /**
     *
     * @type {number}
     * @memberof MarginAccountTradeListResponseInner
     */
    id?: number;
    /**
     *
     * @type {boolean}
     * @memberof MarginAccountTradeListResponseInner
     */
    isBestMatch?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof MarginAccountTradeListResponseInner
     */
    isBuyer?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof MarginAccountTradeListResponseInner
     */
    isMaker?: boolean;
    /**
     *
     * @type {number}
     * @memberof MarginAccountTradeListResponseInner
     */
    orderId?: number;
    /**
     *
     * @type {string}
     * @memberof MarginAccountTradeListResponseInner
     */
    price?: string;
    /**
     *
     * @type {string}
     * @memberof MarginAccountTradeListResponseInner
     */
    qty?: string;
    /**
     *
     * @type {string}
     * @memberof MarginAccountTradeListResponseInner
     */
    symbol?: string;
    /**
     *
     * @type {number}
     * @memberof MarginAccountTradeListResponseInner
     */
    time?: number;
}
