/* tslint:disable */
/* eslint-disable */

/**
 * Binance Public Derivatives Trading Portfolio Margin REST API
 *
 * OpenAPI Specification for the Binance Public Derivatives Trading Portfolio Margin REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PortfolioMarginUmTradingQuantitativeRulesIndicatorsResponse2IndicatorsACCOUNTInner } from './portfolio-margin-um-trading-quantitative-rules-indicators-response2-indicators-accountinner';

/**
 *
 * @export
 * @interface PortfolioMarginUmTradingQuantitativeRulesIndicatorsResponse2Indicators
 */
export interface PortfolioMarginUmTradingQuantitativeRulesIndicatorsResponse2Indicators {
    /**
     *
     * @type {Array<PortfolioMarginUmTradingQuantitativeRulesIndicatorsResponse2IndicatorsACCOUNTInner>}
     * @memberof PortfolioMarginUmTradingQuantitativeRulesIndicatorsResponse2Indicators
     */
    ACCOUNT?: Array<PortfolioMarginUmTradingQuantitativeRulesIndicatorsResponse2IndicatorsACCOUNTInner>;
}
