/* tslint:disable */

/**
 * Binance Derivatives Trading Portfolio Margin REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QueryUmPositionInformationResponse2Inner
 */
export interface QueryUmPositionInformationResponse2Inner {
    /**
     *
     * @type {string}
     * @memberof QueryUmPositionInformationResponse2Inner
     */
    symbol?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmPositionInformationResponse2Inner
     */
    positionAmt?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmPositionInformationResponse2Inner
     */
    entryPrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmPositionInformationResponse2Inner
     */
    markPrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmPositionInformationResponse2Inner
     */
    unRealizedProfit?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmPositionInformationResponse2Inner
     */
    liquidationPrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmPositionInformationResponse2Inner
     */
    leverage?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmPositionInformationResponse2Inner
     */
    maxNotionalValue?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmPositionInformationResponse2Inner
     */
    positionSide?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmPositionInformationResponse2Inner
     */
    notional?: string;
    /**
     *
     * @type {number}
     * @memberof QueryUmPositionInformationResponse2Inner
     */
    updateTime?: number;
}
