/* tslint:disable */

/**
 * Binance Public Derivatives Trading Portfolio Margin REST API
 *
 * OpenAPI Specification for the Binance Public Derivatives Trading Portfolio Margin REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UmFuturesAccountConfigurationResponse
 */
export interface UmFuturesAccountConfigurationResponse {
    /**
     *
     * @type {number}
     * @memberof UmFuturesAccountConfigurationResponse
     */
    feeTier?: number;
    /**
     *
     * @type {boolean}
     * @memberof UmFuturesAccountConfigurationResponse
     */
    canTrade?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof UmFuturesAccountConfigurationResponse
     */
    canDeposit?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof UmFuturesAccountConfigurationResponse
     */
    canWithdraw?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof UmFuturesAccountConfigurationResponse
     */
    dualSidePosition?: boolean;
    /**
     *
     * @type {number}
     * @memberof UmFuturesAccountConfigurationResponse
     */
    updateTime?: number;
    /**
     *
     * @type {boolean}
     * @memberof UmFuturesAccountConfigurationResponse
     */
    multiAssetsMargin?: boolean;
    /**
     *
     * @type {number}
     * @memberof UmFuturesAccountConfigurationResponse
     */
    tradeGroupId?: number;
}
