/* tslint:disable */

/**
 * Binance Derivatives Trading Portfolio Margin WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ConditionalOrderTradeUpdateSo
 */
export interface ConditionalOrderTradeUpdateSo {
    /**
     *
     * @type {string}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    s?: string;
    /**
     *
     * @type {string}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    c?: string;
    /**
     *
     * @type {number}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    si?: number;
    /**
     *
     * @type {string}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    S?: string;
    /**
     *
     * @type {string}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    st?: string;
    /**
     *
     * @type {string}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    f?: string;
    /**
     *
     * @type {string}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    q?: string;
    /**
     *
     * @type {string}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    p?: string;
    /**
     *
     * @type {string}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    sp?: string;
    /**
     *
     * @type {string}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    os?: string;
    /**
     *
     * @type {number}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    T?: number;
    /**
     *
     * @type {number}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    ut?: number;
    /**
     *
     * @type {boolean}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    R?: boolean;
    /**
     *
     * @type {string}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    wt?: string;
    /**
     *
     * @type {string}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    ps?: string;
    /**
     *
     * @type {boolean}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    cp?: boolean;
    /**
     *
     * @type {string}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    AP?: string;
    /**
     *
     * @type {string}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    cr?: string;
    /**
     *
     * @type {number}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    i?: number;
    /**
     *
     * @type {string}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    V?: string;
    /**
     *
     * @type {number}
     * @memberof ConditionalOrderTradeUpdateSo
     */
    gtd?: number;
}
