/* tslint:disable */
/* eslint-disable */

/**
 * Binance Spot WebSocket API
 *
 * OpenAPI Specifications for the Binance Spot WebSocket API
 *
 * API documents:
 * - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)
 * - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ExchangeInfoResponseRateLimitsInner } from './exchange-info-response-rate-limits-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderTestResponse2Result } from './order-test-response2-result';

/**
 *
 * @export
 * @interface SorOrderTestResponse2
 */
export interface SorOrderTestResponse2 {
    /**
     *
     * @type {string}
     * @memberof SorOrderTestResponse2
     */
    id?: string;
    /**
     *
     * @type {number}
     * @memberof SorOrderTestResponse2
     */
    status?: number;
    /**
     *
     * @type {OrderTestResponse2Result}
     * @memberof SorOrderTestResponse2
     */
    result?: OrderTestResponse2Result;
    /**
     *
     * @type {Array<ExchangeInfoResponseRateLimitsInner>}
     * @memberof SorOrderTestResponse2
     */
    rateLimits?: Array<ExchangeInfoResponseRateLimitsInner>;
}
