/* tslint:disable */

/**
 * Binance Public Wallet REST API
 *
 * OpenAPI Specification for the Binance Public Wallet REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AssetDividendRecordResponseRowsInner
 */
export interface AssetDividendRecordResponseRowsInner {
    /**
     *
     * @type {number}
     * @memberof AssetDividendRecordResponseRowsInner
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof AssetDividendRecordResponseRowsInner
     */
    amount?: string;
    /**
     *
     * @type {string}
     * @memberof AssetDividendRecordResponseRowsInner
     */
    asset?: string;
    /**
     *
     * @type {number}
     * @memberof AssetDividendRecordResponseRowsInner
     */
    divTime?: number;
    /**
     *
     * @type {string}
     * @memberof AssetDividendRecordResponseRowsInner
     */
    enInfo?: string;
    /**
     *
     * @type {number}
     * @memberof AssetDividendRecordResponseRowsInner
     */
    tranId?: number;
}
