/* tslint:disable */
/* eslint-disable */

/**
 * Binance Public Wallet REST API
 *
 * OpenAPI Specification for the Binance Public Wallet REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { DailyAccountSnapshotResponse3SnapshotVosInner } from './daily-account-snapshot-response3-snapshot-vos-inner';

/**
 *
 * @export
 * @interface DailyAccountSnapshotResponse3
 */
export interface DailyAccountSnapshotResponse3 {
    /**
     *
     * @type {number}
     * @memberof DailyAccountSnapshotResponse3
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof DailyAccountSnapshotResponse3
     */
    msg?: string;
    /**
     *
     * @type {Array<DailyAccountSnapshotResponse3SnapshotVosInner>}
     * @memberof DailyAccountSnapshotResponse3
     */
    snapshotVos?: Array<DailyAccountSnapshotResponse3SnapshotVosInner>;
}
