/* tslint:disable */

/**
 * Binance Public Wallet REST API
 *
 * OpenAPI Specification for the Binance Public Wallet REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetCloudMiningPaymentAndRefundHistoryResponseRowsInner
 */
export interface GetCloudMiningPaymentAndRefundHistoryResponseRowsInner {
    /**
     *
     * @type {number}
     * @memberof GetCloudMiningPaymentAndRefundHistoryResponseRowsInner
     */
    createTime?: number;
    /**
     *
     * @type {number}
     * @memberof GetCloudMiningPaymentAndRefundHistoryResponseRowsInner
     */
    tranId?: number;
    /**
     *
     * @type {number}
     * @memberof GetCloudMiningPaymentAndRefundHistoryResponseRowsInner
     */
    type?: number;
    /**
     *
     * @type {string}
     * @memberof GetCloudMiningPaymentAndRefundHistoryResponseRowsInner
     */
    asset?: string;
    /**
     *
     * @type {string}
     * @memberof GetCloudMiningPaymentAndRefundHistoryResponseRowsInner
     */
    amount?: string;
    /**
     *
     * @type {string}
     * @memberof GetCloudMiningPaymentAndRefundHistoryResponseRowsInner
     */
    status?: string;
}
