/* tslint:disable */

/**
 * Binance Public Wallet REST API
 *
 * OpenAPI Specification for the Binance Public Wallet REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetSpotDelistScheduleResponseInner
 */
export interface GetSpotDelistScheduleResponseInner {
    /**
     *
     * @type {number}
     * @memberof GetSpotDelistScheduleResponseInner
     */
    delistTime?: number;
    /**
     *
     * @type {Array<string>}
     * @memberof GetSpotDelistScheduleResponseInner
     */
    symbols?: Array<string>;
}
