/* tslint:disable */
/* eslint-disable */

/**
 * Binance Public Wallet REST API
 *
 * OpenAPI Specification for the Binance Public Wallet REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OnboardedVaspListResponseInner } from './onboarded-vasp-list-response-inner';

/**
 *
 * @export
 * @interface OnboardedVaspListResponse
 */
export interface OnboardedVaspListResponse extends Array<OnboardedVaspListResponseInner> {}
