/* tslint:disable */

/**
 * Binance Spot REST API
 *
 * OpenAPI Specifications for the Binance Spot REST API
 *
 * API documents:
 * - [Github rest-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md)
 * - [General API information for rest-api on website](https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information)
 *
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ExchangeFiltersInner
 */
export interface ExchangeFiltersInner {
    /**
     *
     * @type {string}
     * @memberof ExchangeFiltersInner
     */
    filterType?: string;
    /**
     *
     * @type {string}
     * @memberof ExchangeFiltersInner
     */
    minPrice?: string;
    /**
     *
     * @type {string}
     * @memberof ExchangeFiltersInner
     */
    maxPrice?: string;
    /**
     *
     * @type {string}
     * @memberof ExchangeFiltersInner
     */
    tickSize?: string;
    /**
     *
     * @type {string}
     * @memberof ExchangeFiltersInner
     */
    multiplierUp?: string;
    /**
     *
     * @type {string}
     * @memberof ExchangeFiltersInner
     */
    multiplierDown?: string;
    /**
     *
     * @type {number}
     * @memberof ExchangeFiltersInner
     */
    avgPriceMins?: number;
    /**
     *
     * @type {string}
     * @memberof ExchangeFiltersInner
     */
    bidMultiplierUp?: string;
    /**
     *
     * @type {string}
     * @memberof ExchangeFiltersInner
     */
    bidMultiplierDown?: string;
    /**
     *
     * @type {string}
     * @memberof ExchangeFiltersInner
     */
    askMultiplierUp?: string;
    /**
     *
     * @type {string}
     * @memberof ExchangeFiltersInner
     */
    askMultiplierDown?: string;
    /**
     *
     * @type {string}
     * @memberof ExchangeFiltersInner
     */
    minQty?: string;
    /**
     *
     * @type {string}
     * @memberof ExchangeFiltersInner
     */
    maxQty?: string;
    /**
     *
     * @type {string}
     * @memberof ExchangeFiltersInner
     */
    stepSize?: string;
    /**
     *
     * @type {string}
     * @memberof ExchangeFiltersInner
     */
    minNotional?: string;
    /**
     *
     * @type {boolean}
     * @memberof ExchangeFiltersInner
     */
    applyToMarket?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ExchangeFiltersInner
     */
    applyMinToMarket?: boolean;
    /**
     *
     * @type {string}
     * @memberof ExchangeFiltersInner
     */
    maxNotional?: string;
    /**
     *
     * @type {boolean}
     * @memberof ExchangeFiltersInner
     */
    applyMaxToMarket?: boolean;
    /**
     *
     * @type {number}
     * @memberof ExchangeFiltersInner
     */
    limit?: number;
    /**
     *
     * @type {number}
     * @memberof ExchangeFiltersInner
     */
    maxNumOrders?: number;
    /**
     *
     * @type {number}
     * @memberof ExchangeFiltersInner
     */
    maxNumAlgoOrders?: number;
    /**
     *
     * @type {number}
     * @memberof ExchangeFiltersInner
     */
    maxNumIcebergOrders?: number;
    /**
     *
     * @type {string}
     * @memberof ExchangeFiltersInner
     */
    maxPosition?: string;
    /**
     *
     * @type {number}
     * @memberof ExchangeFiltersInner
     */
    minTrailingAboveDelta?: number;
    /**
     *
     * @type {number}
     * @memberof ExchangeFiltersInner
     */
    maxTrailingAboveDelta?: number;
    /**
     *
     * @type {number}
     * @memberof ExchangeFiltersInner
     */
    minTrailingBelowDelta?: number;
    /**
     *
     * @type {number}
     * @memberof ExchangeFiltersInner
     */
    maxTrailingBelowDelta?: number;
}
