/* tslint:disable */

/**
 * Binance Public Spot REST API
 *
 * OpenAPI Specifications for the Binance Public Spot REST API
 *
 * API documents:
 * - [Github rest-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md)
 * - [General API information for rest-api on website](https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information)
 *
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrderListOcoResponseOrderReportsInner
 */
export interface OrderListOcoResponseOrderReportsInner {
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    symbol?: string;
    /**
     *
     * @type {number}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    orderId?: number;
    /**
     *
     * @type {number}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    orderListId?: number;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    clientOrderId?: string;
    /**
     *
     * @type {number}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    transactTime?: number;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    price?: string;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    origQty?: string;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    executedQty?: string;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    origQuoteOrderQty?: string;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    cummulativeQuoteQty?: string;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    timeInForce?: string;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    type?: string;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    side?: string;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    stopPrice?: string;
    /**
     *
     * @type {number}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    workingTime?: number;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    icebergQty?: string;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponseOrderReportsInner
     */
    selfTradePreventionMode?: string;
}
