/* tslint:disable */

/**
 * Binance Spot REST API
 *
 * OpenAPI Specifications for the Binance Spot REST API
 *
 * API documents:
 * - [Github rest-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md)
 * - [General API information for rest-api on website](https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information)
 *
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Ticker24hrResponse2Inner
 */
export interface Ticker24hrResponse2Inner {
    /**
     *
     * @type {string}
     * @memberof Ticker24hrResponse2Inner
     */
    symbol?: string;
    /**
     *
     * @type {string}
     * @memberof Ticker24hrResponse2Inner
     */
    openPrice?: string;
    /**
     *
     * @type {string}
     * @memberof Ticker24hrResponse2Inner
     */
    highPrice?: string;
    /**
     *
     * @type {string}
     * @memberof Ticker24hrResponse2Inner
     */
    lowPrice?: string;
    /**
     *
     * @type {string}
     * @memberof Ticker24hrResponse2Inner
     */
    lastPrice?: string;
    /**
     *
     * @type {string}
     * @memberof Ticker24hrResponse2Inner
     */
    volume?: string;
    /**
     *
     * @type {string}
     * @memberof Ticker24hrResponse2Inner
     */
    quoteVolume?: string;
    /**
     *
     * @type {number}
     * @memberof Ticker24hrResponse2Inner
     */
    openTime?: number;
    /**
     *
     * @type {number}
     * @memberof Ticker24hrResponse2Inner
     */
    closeTime?: number;
    /**
     *
     * @type {number}
     * @memberof Ticker24hrResponse2Inner
     */
    firstId?: number;
    /**
     *
     * @type {number}
     * @memberof Ticker24hrResponse2Inner
     */
    lastId?: number;
    /**
     *
     * @type {number}
     * @memberof Ticker24hrResponse2Inner
     */
    count?: number;
}
