/* tslint:disable */

/**
 * Binance Auto Invest REST API
 *
 * OpenAPI Specification for the Binance Auto Invest REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface IndexLinkedPlanRedemptionTradeResponseInner
 */
export interface IndexLinkedPlanRedemptionTradeResponseInner {
    /**
     *
     * @type {number}
     * @memberof IndexLinkedPlanRedemptionTradeResponseInner
     */
    indexId?: number;
    /**
     *
     * @type {string}
     * @memberof IndexLinkedPlanRedemptionTradeResponseInner
     */
    indexName?: string;
    /**
     *
     * @type {number}
     * @memberof IndexLinkedPlanRedemptionTradeResponseInner
     */
    redemptionId?: number;
    /**
     *
     * @type {string}
     * @memberof IndexLinkedPlanRedemptionTradeResponseInner
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof IndexLinkedPlanRedemptionTradeResponseInner
     */
    asset?: string;
    /**
     *
     * @type {string}
     * @memberof IndexLinkedPlanRedemptionTradeResponseInner
     */
    amount?: string;
    /**
     *
     * @type {number}
     * @memberof IndexLinkedPlanRedemptionTradeResponseInner
     */
    redemptionDateTime?: number;
    /**
     *
     * @type {string}
     * @memberof IndexLinkedPlanRedemptionTradeResponseInner
     */
    transactionFee?: string;
    /**
     *
     * @type {string}
     * @memberof IndexLinkedPlanRedemptionTradeResponseInner
     */
    transactionFeeUnit?: string;
}
