/* tslint:disable */

/**
 * Binance Public Auto Invest REST API
 *
 * OpenAPI Specification for the Binance Public Auto Invest REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InvestmentPlanCreationResponse
 */
export interface InvestmentPlanCreationResponse {
    /**
     *
     * @type {number}
     * @memberof InvestmentPlanCreationResponse
     */
    planId?: number;
    /**
     *
     * @type {number}
     * @memberof InvestmentPlanCreationResponse
     */
    nextExecutionDateTime?: number;
}
