/* tslint:disable */
/* eslint-disable */

/**
 * Binance Public Auto Invest REST API
 *
 * OpenAPI Specification for the Binance Public Auto Invest REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { QueryIndexDetailsResponseAssetAllocationInner } from './query-index-details-response-asset-allocation-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { QueryIndexLinkedPlanPositionDetailsResponseDetailsInner } from './query-index-linked-plan-position-details-response-details-inner';

/**
 *
 * @export
 * @interface QueryIndexLinkedPlanPositionDetailsResponse
 */
export interface QueryIndexLinkedPlanPositionDetailsResponse {
    /**
     *
     * @type {number}
     * @memberof QueryIndexLinkedPlanPositionDetailsResponse
     */
    indexId?: number;
    /**
     *
     * @type {string}
     * @memberof QueryIndexLinkedPlanPositionDetailsResponse
     */
    totalInvestedInUSD?: string;
    /**
     *
     * @type {string}
     * @memberof QueryIndexLinkedPlanPositionDetailsResponse
     */
    currentInvestedInUSD?: string;
    /**
     *
     * @type {string}
     * @memberof QueryIndexLinkedPlanPositionDetailsResponse
     */
    pnlInUSD?: string;
    /**
     *
     * @type {string}
     * @memberof QueryIndexLinkedPlanPositionDetailsResponse
     */
    roi?: string;
    /**
     *
     * @type {Array<QueryIndexDetailsResponseAssetAllocationInner>}
     * @memberof QueryIndexLinkedPlanPositionDetailsResponse
     */
    assetAllocation?: Array<QueryIndexDetailsResponseAssetAllocationInner>;
    /**
     *
     * @type {Array<QueryIndexLinkedPlanPositionDetailsResponseDetailsInner>}
     * @memberof QueryIndexLinkedPlanPositionDetailsResponse
     */
    details?: Array<QueryIndexLinkedPlanPositionDetailsResponseDetailsInner>;
}
