/* tslint:disable */

/**
 * Binance Public Sub Account REST API
 *
 * OpenAPI Specification for the Binance Public Sub Account REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DeleteIpListForASubAccountApiKeyResponse
 */
export interface DeleteIpListForASubAccountApiKeyResponse {
    /**
     *
     * @type {string}
     * @memberof DeleteIpListForASubAccountApiKeyResponse
     */
    ipRestrict?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof DeleteIpListForASubAccountApiKeyResponse
     */
    ipList?: Array<string>;
    /**
     *
     * @type {number}
     * @memberof DeleteIpListForASubAccountApiKeyResponse
     */
    updateTime?: number;
    /**
     *
     * @type {string}
     * @memberof DeleteIpListForASubAccountApiKeyResponse
     */
    apiKey?: string;
}
