/* tslint:disable */

/**
 * Binance Sub Account REST API
 *
 * OpenAPI Specification for the Binance Sub Account REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EnableLeverageTokenForSubAccountResponse
 */
export interface EnableLeverageTokenForSubAccountResponse {
    /**
     *
     * @type {string}
     * @memberof EnableLeverageTokenForSubAccountResponse
     */
    email?: string;
    /**
     *
     * @type {boolean}
     * @memberof EnableLeverageTokenForSubAccountResponse
     */
    enableBlvt?: boolean;
}
