/* tslint:disable */
/* eslint-disable */

/**
 * Binance Public Sub Account REST API
 *
 * OpenAPI Specification for the Binance Public Sub Account REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetFuturesPositionRiskOfSubAccountV2Response1FuturePositionRiskVosInner } from './get-futures-position-risk-of-sub-account-v2-response1-future-position-risk-vos-inner';

/**
 *
 * @export
 * @interface GetFuturesPositionRiskOfSubAccountV2Response1
 */
export interface GetFuturesPositionRiskOfSubAccountV2Response1 {
    /**
     *
     * @type {Array<GetFuturesPositionRiskOfSubAccountV2Response1FuturePositionRiskVosInner>}
     * @memberof GetFuturesPositionRiskOfSubAccountV2Response1
     */
    futurePositionRiskVos?: Array<GetFuturesPositionRiskOfSubAccountV2Response1FuturePositionRiskVosInner>;
}
