/* tslint:disable */

/**
 * Binance Public Sub Account REST API
 *
 * OpenAPI Specification for the Binance Public Sub Account REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QuerySubAccountAssetsResponseBalancesInner
 */
export interface QuerySubAccountAssetsResponseBalancesInner {
    /**
     *
     * @type {number}
     * @memberof QuerySubAccountAssetsResponseBalancesInner
     */
    freeze?: number;
    /**
     *
     * @type {number}
     * @memberof QuerySubAccountAssetsResponseBalancesInner
     */
    withdrawing?: number;
    /**
     *
     * @type {string}
     * @memberof QuerySubAccountAssetsResponseBalancesInner
     */
    asset?: string;
    /**
     *
     * @type {number}
     * @memberof QuerySubAccountAssetsResponseBalancesInner
     */
    free?: number;
    /**
     *
     * @type {number}
     * @memberof QuerySubAccountAssetsResponseBalancesInner
     */
    locked?: number;
}
