/* tslint:disable */
/* eslint-disable */
/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Binance Sub Account REST API
 *
 * OpenAPI Specification for the Binance Sub Account REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { QuerySubAccountTransactionStatisticsResponse1 } from './query-sub-account-transaction-statistics-response1';
// May contain unused imports in some cases
// @ts-ignore
import type { QuerySubAccountTransactionStatisticsResponse2 } from './query-sub-account-transaction-statistics-response2';
// May contain unused imports in some cases
// @ts-ignore
import type { QuerySubAccountTransactionStatisticsResponse2TradeInfoVosInner } from './query-sub-account-transaction-statistics-response2-trade-info-vos-inner';

/**
 * @type QuerySubAccountTransactionStatisticsResponse
 * @export
 */
export type QuerySubAccountTransactionStatisticsResponse =
    | QuerySubAccountTransactionStatisticsResponse1
    | QuerySubAccountTransactionStatisticsResponse2;
