/* tslint:disable */

/**
 * Binance Public Sub Account REST API
 *
 * OpenAPI Specification for the Binance Public Sub Account REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SubAccountTransferHistoryResponseInner
 */
export interface SubAccountTransferHistoryResponseInner {
    /**
     *
     * @type {string}
     * @memberof SubAccountTransferHistoryResponseInner
     */
    counterParty?: string;
    /**
     *
     * @type {string}
     * @memberof SubAccountTransferHistoryResponseInner
     */
    email?: string;
    /**
     *
     * @type {number}
     * @memberof SubAccountTransferHistoryResponseInner
     */
    type?: number;
    /**
     *
     * @type {string}
     * @memberof SubAccountTransferHistoryResponseInner
     */
    asset?: string;
    /**
     *
     * @type {string}
     * @memberof SubAccountTransferHistoryResponseInner
     */
    qty?: string;
    /**
     *
     * @type {string}
     * @memberof SubAccountTransferHistoryResponseInner
     */
    fromAccountType?: string;
    /**
     *
     * @type {string}
     * @memberof SubAccountTransferHistoryResponseInner
     */
    toAccountType?: string;
    /**
     *
     * @type {string}
     * @memberof SubAccountTransferHistoryResponseInner
     */
    status?: string;
    /**
     *
     * @type {number}
     * @memberof SubAccountTransferHistoryResponseInner
     */
    tranId?: number;
    /**
     *
     * @type {number}
     * @memberof SubAccountTransferHistoryResponseInner
     */
    time?: number;
}
