/* tslint:disable */
/* eslint-disable */

/**
 * Binance Public Derivatives Trading USDS Futures WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Public Derivatives Trading USDS Futures WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CompositeIndexSymbolInformationStreamsResponseCInner } from './composite-index-symbol-information-streams-response-cinner';

/**
 *
 * @export
 * @interface CompositeIndexSymbolInformationStreamsResponse
 */
export interface CompositeIndexSymbolInformationStreamsResponse {
    /**
     *
     * @type {string}
     * @memberof CompositeIndexSymbolInformationStreamsResponse
     */
    e?: string;
    /**
     *
     * @type {number}
     * @memberof CompositeIndexSymbolInformationStreamsResponse
     */
    E?: number;
    /**
     *
     * @type {string}
     * @memberof CompositeIndexSymbolInformationStreamsResponse
     */
    s?: string;
    /**
     *
     * @type {string}
     * @memberof CompositeIndexSymbolInformationStreamsResponse
     */
    p?: string;
    /**
     *
     * @type {string}
     * @memberof CompositeIndexSymbolInformationStreamsResponse
     */
    C?: string;
    /**
     *
     * @type {Array<CompositeIndexSymbolInformationStreamsResponseCInner>}
     * @memberof CompositeIndexSymbolInformationStreamsResponse
     */
    c?: Array<CompositeIndexSymbolInformationStreamsResponseCInner>;
}
