/* tslint:disable */

/**
 * Binance Derivatives Trading USDS Futures WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Derivatives Trading USDS Futures WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TradeLite
 */
export interface TradeLite {
    /**
     *
     * @type {number}
     * @memberof TradeLite
     */
    E?: number;
    /**
     *
     * @type {number}
     * @memberof TradeLite
     */
    T?: number;
    /**
     *
     * @type {string}
     * @memberof TradeLite
     */
    s?: string;
    /**
     *
     * @type {string}
     * @memberof TradeLite
     */
    q?: string;
    /**
     *
     * @type {string}
     * @memberof TradeLite
     */
    p?: string;
    /**
     *
     * @type {boolean}
     * @memberof TradeLite
     */
    m?: boolean;
    /**
     *
     * @type {string}
     * @memberof TradeLite
     */
    c?: string;
    /**
     *
     * @type {string}
     * @memberof TradeLite
     */
    S?: string;
    /**
     *
     * @type {string}
     * @memberof TradeLite
     */
    L?: string;
    /**
     *
     * @type {string}
     * @memberof TradeLite
     */
    l?: string;
    /**
     *
     * @type {number}
     * @memberof TradeLite
     */
    t?: number;
    /**
     *
     * @type {number}
     * @memberof TradeLite
     */
    i?: number;
}
