/* tslint:disable */
/* eslint-disable */

/**
 * Binance Public NFT REST API
 *
 * OpenAPI Specification for the Binance Public NFT REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetNFTDepositHistoryResponseListInner } from './get-nftdeposit-history-response-list-inner';

/**
 *
 * @export
 * @interface GetNFTDepositHistoryResponse
 */
export interface GetNFTDepositHistoryResponse {
    /**
     *
     * @type {number}
     * @memberof GetNFTDepositHistoryResponse
     */
    total?: number;
    /**
     *
     * @type {Array<GetNFTDepositHistoryResponseListInner>}
     * @memberof GetNFTDepositHistoryResponse
     */
    list?: Array<GetNFTDepositHistoryResponseListInner>;
}
