/* tslint:disable */

/**
 * Binance Public Margin Trading REST API
 *
 * OpenAPI Specification for the Binance Public Margin Trading REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MarginAccountBorrowRepayResponse
 */
export interface MarginAccountBorrowRepayResponse {
    /**
     *
     * @type {number}
     * @memberof MarginAccountBorrowRepayResponse
     */
    tranId?: number;
}
