/* tslint:disable */

/**
 * Binance Public Margin Trading REST API
 *
 * OpenAPI Specification for the Binance Public Margin Trading REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MarginAccountNewOrderResponse2
 */
export interface MarginAccountNewOrderResponse2 {
    /**
     *
     * @type {string}
     * @memberof MarginAccountNewOrderResponse2
     */
    symbol?: string;
    /**
     *
     * @type {number}
     * @memberof MarginAccountNewOrderResponse2
     */
    orderId?: number;
    /**
     *
     * @type {string}
     * @memberof MarginAccountNewOrderResponse2
     */
    clientOrderId?: string;
    /**
     *
     * @type {number}
     * @memberof MarginAccountNewOrderResponse2
     */
    transactTime?: number;
    /**
     *
     * @type {string}
     * @memberof MarginAccountNewOrderResponse2
     */
    price?: string;
    /**
     *
     * @type {string}
     * @memberof MarginAccountNewOrderResponse2
     */
    origQty?: string;
    /**
     *
     * @type {string}
     * @memberof MarginAccountNewOrderResponse2
     */
    executedQty?: string;
    /**
     *
     * @type {string}
     * @memberof MarginAccountNewOrderResponse2
     */
    cummulativeQuoteQty?: string;
    /**
     *
     * @type {string}
     * @memberof MarginAccountNewOrderResponse2
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof MarginAccountNewOrderResponse2
     */
    timeInForce?: string;
    /**
     *
     * @type {string}
     * @memberof MarginAccountNewOrderResponse2
     */
    type?: string;
    /**
     *
     * @type {string}
     * @memberof MarginAccountNewOrderResponse2
     */
    side?: string;
    /**
     *
     * @type {boolean}
     * @memberof MarginAccountNewOrderResponse2
     */
    isIsolated?: boolean;
    /**
     *
     * @type {string}
     * @memberof MarginAccountNewOrderResponse2
     */
    selfTradePreventionMode?: string;
}
