/* tslint:disable */
/* eslint-disable */

/**
 * Binance Public Margin Trading REST API
 *
 * OpenAPI Specification for the Binance Public Margin Trading REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { QueryIsolatedMarginAccountInfoResponse1AssetsInner } from './query-isolated-margin-account-info-response1-assets-inner';

/**
 *
 * @export
 * @interface QueryIsolatedMarginAccountInfoResponse1
 */
export interface QueryIsolatedMarginAccountInfoResponse1 {
    /**
     *
     * @type {Array<QueryIsolatedMarginAccountInfoResponse1AssetsInner>}
     * @memberof QueryIsolatedMarginAccountInfoResponse1
     */
    assets?: Array<QueryIsolatedMarginAccountInfoResponse1AssetsInner>;
    /**
     *
     * @type {string}
     * @memberof QueryIsolatedMarginAccountInfoResponse1
     */
    totalAssetOfBtc?: string;
    /**
     *
     * @type {string}
     * @memberof QueryIsolatedMarginAccountInfoResponse1
     */
    totalLiabilityOfBtc?: string;
    /**
     *
     * @type {string}
     * @memberof QueryIsolatedMarginAccountInfoResponse1
     */
    totalNetAssetOfBtc?: string;
}
