/* tslint:disable */
/* eslint-disable */

/**
 * Binance Public Margin Trading REST API
 *
 * OpenAPI Specification for the Binance Public Margin Trading REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { QueryMarginAccountsOpenOcoResponseInnerOrdersInner } from './query-margin-accounts-open-oco-response-inner-orders-inner';

/**
 *
 * @export
 * @interface QueryMarginAccountsOpenOcoResponseInner
 */
export interface QueryMarginAccountsOpenOcoResponseInner {
    /**
     *
     * @type {number}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    orderListId?: number;
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    contingencyType?: string;
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    listStatusType?: string;
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    listOrderStatus?: string;
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    listClientOrderId?: string;
    /**
     *
     * @type {number}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    transactionTime?: number;
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    symbol?: string;
    /**
     *
     * @type {boolean}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    isIsolated?: boolean;
    /**
     *
     * @type {Array<QueryMarginAccountsOpenOcoResponseInnerOrdersInner>}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    orders?: Array<QueryMarginAccountsOpenOcoResponseInnerOrdersInner>;
}
