/* tslint:disable */

/**
 * Binance Public Staking REST API
 *
 * OpenAPI Specification for the Binance Public Staking REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetCurrentEthStakingQuotaResponse
 */
export interface GetCurrentEthStakingQuotaResponse {
    /**
     *
     * @type {string}
     * @memberof GetCurrentEthStakingQuotaResponse
     */
    leftStakingPersonalQuota?: string;
    /**
     *
     * @type {string}
     * @memberof GetCurrentEthStakingQuotaResponse
     */
    leftRedemptionPersonalQuota?: string;
}
