/* tslint:disable */

/**
 * Binance Derivatives Trading Options REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Options REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CancelMultipleOptionOrdersResponseInner
 */
export interface CancelMultipleOptionOrdersResponseInner {
    /**
     *
     * @type {number}
     * @memberof CancelMultipleOptionOrdersResponseInner
     */
    orderId?: number;
    /**
     *
     * @type {string}
     * @memberof CancelMultipleOptionOrdersResponseInner
     */
    symbol?: string;
    /**
     *
     * @type {string}
     * @memberof CancelMultipleOptionOrdersResponseInner
     */
    price?: string;
    /**
     *
     * @type {string}
     * @memberof CancelMultipleOptionOrdersResponseInner
     */
    quantity?: string;
    /**
     *
     * @type {string}
     * @memberof CancelMultipleOptionOrdersResponseInner
     */
    executedQty?: string;
    /**
     *
     * @type {number}
     * @memberof CancelMultipleOptionOrdersResponseInner
     */
    fee?: number;
    /**
     *
     * @type {string}
     * @memberof CancelMultipleOptionOrdersResponseInner
     */
    side?: string;
    /**
     *
     * @type {string}
     * @memberof CancelMultipleOptionOrdersResponseInner
     */
    type?: string;
    /**
     *
     * @type {string}
     * @memberof CancelMultipleOptionOrdersResponseInner
     */
    timeInForce?: string;
    /**
     *
     * @type {number}
     * @memberof CancelMultipleOptionOrdersResponseInner
     */
    createTime?: number;
    /**
     *
     * @type {string}
     * @memberof CancelMultipleOptionOrdersResponseInner
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof CancelMultipleOptionOrdersResponseInner
     */
    avgPrice?: string;
    /**
     *
     * @type {boolean}
     * @memberof CancelMultipleOptionOrdersResponseInner
     */
    reduceOnly?: boolean;
    /**
     *
     * @type {string}
     * @memberof CancelMultipleOptionOrdersResponseInner
     */
    clientOrderId?: string;
    /**
     *
     * @type {number}
     * @memberof CancelMultipleOptionOrdersResponseInner
     */
    updateTime?: number;
}
