/* tslint:disable */
/* eslint-disable */

/**
 * Binance Derivatives Trading Options REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Options REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetOptionTransactionHistoryDownloadLinkByIdResponse1 } from './get-option-transaction-history-download-link-by-id-response1';
// May contain unused imports in some cases
// @ts-ignore
import type { GetOptionTransactionHistoryDownloadLinkByIdResponse2 } from './get-option-transaction-history-download-link-by-id-response2';

/**
 * @type GetOptionTransactionHistoryDownloadLinkByIdResponse
 * @export
 */
export type GetOptionTransactionHistoryDownloadLinkByIdResponse =
    | GetOptionTransactionHistoryDownloadLinkByIdResponse1
    | GetOptionTransactionHistoryDownloadLinkByIdResponse2;
