/* tslint:disable */

/**
 * Binance Public Derivatives Trading Options REST API
 *
 * OpenAPI Specification for the Binance Public Derivatives Trading Options REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RecentBlockTradesListResponseInner
 */
export interface RecentBlockTradesListResponseInner {
    /**
     *
     * @type {number}
     * @memberof RecentBlockTradesListResponseInner
     */
    id?: number;
    /**
     *
     * @type {number}
     * @memberof RecentBlockTradesListResponseInner
     */
    tradeId?: number;
    /**
     *
     * @type {string}
     * @memberof RecentBlockTradesListResponseInner
     */
    symbol?: string;
    /**
     *
     * @type {string}
     * @memberof RecentBlockTradesListResponseInner
     */
    price?: string;
    /**
     *
     * @type {string}
     * @memberof RecentBlockTradesListResponseInner
     */
    qty?: string;
    /**
     *
     * @type {string}
     * @memberof RecentBlockTradesListResponseInner
     */
    quoteQty?: string;
    /**
     *
     * @type {number}
     * @memberof RecentBlockTradesListResponseInner
     */
    side?: number;
    /**
     *
     * @type {number}
     * @memberof RecentBlockTradesListResponseInner
     */
    time?: number;
}
