/* tslint:disable */

/**
 * Binance Public Derivatives Trading Portfolio Margin Pro REST API
 *
 * OpenAPI Specification for the Binance Public Derivatives Trading Portfolio Margin Pro REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MintBfusdForPortfolioMarginResponse
 */
export interface MintBfusdForPortfolioMarginResponse {
    /**
     *
     * @type {string}
     * @memberof MintBfusdForPortfolioMarginResponse
     */
    fromAsset?: string;
    /**
     *
     * @type {string}
     * @memberof MintBfusdForPortfolioMarginResponse
     */
    targetAsset?: string;
    /**
     *
     * @type {number}
     * @memberof MintBfusdForPortfolioMarginResponse
     */
    fromAssetQty?: number;
    /**
     *
     * @type {number}
     * @memberof MintBfusdForPortfolioMarginResponse
     */
    targetAssetQty?: number;
    /**
     *
     * @type {number}
     * @memberof MintBfusdForPortfolioMarginResponse
     */
    rate?: number;
}
