/* tslint:disable */

/**
 * Binance Crypto Loan REST API
 *
 * OpenAPI Specification for the Binance Crypto Loan REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CryptoLoanRepayResponse2
 */
export interface CryptoLoanRepayResponse2 {
    /**
     *
     * @type {string}
     * @memberof CryptoLoanRepayResponse2
     */
    loanCoin?: string;
    /**
     *
     * @type {string}
     * @memberof CryptoLoanRepayResponse2
     */
    collateralCoin?: string;
    /**
     *
     * @type {string}
     * @memberof CryptoLoanRepayResponse2
     */
    repayStatus?: string;
}
