/* tslint:disable */

/**
 * Binance Public Crypto Loan REST API
 *
 * OpenAPI Specification for the Binance Public Crypto Loan REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CryptoLoanAdjustLtvResponse
 */
export interface CryptoLoanAdjustLtvResponse {
    /**
     *
     * @type {string}
     * @memberof CryptoLoanAdjustLtvResponse
     */
    loanCoin?: string;
    /**
     *
     * @type {string}
     * @memberof CryptoLoanAdjustLtvResponse
     */
    collateralCoin?: string;
    /**
     *
     * @type {string}
     * @memberof CryptoLoanAdjustLtvResponse
     */
    direction?: string;
    /**
     *
     * @type {string}
     * @memberof CryptoLoanAdjustLtvResponse
     */
    amount?: string;
    /**
     *
     * @type {string}
     * @memberof CryptoLoanAdjustLtvResponse
     */
    currentLTV?: string;
}
