/* tslint:disable */
/* eslint-disable */
/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Binance Derivatives Trading USDS Futures WebSocket API
 *
 * OpenAPI Specification for the Binance Derivatives Trading USDS Futures WebSocket API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AccountInformationV2Response1 } from './account-information-v2-response1';
// May contain unused imports in some cases
// @ts-ignore
import type { AccountInformationV2Response1RateLimitsInner } from './account-information-v2-response1-rate-limits-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { AccountInformationV2Response2 } from './account-information-v2-response2';
// May contain unused imports in some cases
// @ts-ignore
import type { AccountInformationV2Response2Result } from './account-information-v2-response2-result';

/**
 * @type AccountInformationV2Response
 * @export
 */
export type AccountInformationV2Response =
    | AccountInformationV2Response1
    | AccountInformationV2Response2;
