/* tslint:disable */

/**
 * Binance Public Derivatives Trading USDS Futures WebSocket API
 *
 * OpenAPI Specification for the Binance Public Derivatives Trading USDS Futures WebSocket API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SymbolOrderBookTickerResponse1RateLimitsInner
 */
export interface SymbolOrderBookTickerResponse1RateLimitsInner {
    /**
     *
     * @type {string}
     * @memberof SymbolOrderBookTickerResponse1RateLimitsInner
     */
    rateLimitType?: string;
    /**
     *
     * @type {string}
     * @memberof SymbolOrderBookTickerResponse1RateLimitsInner
     */
    interval?: string;
    /**
     *
     * @type {number}
     * @memberof SymbolOrderBookTickerResponse1RateLimitsInner
     */
    intervalNum?: number;
    /**
     *
     * @type {number}
     * @memberof SymbolOrderBookTickerResponse1RateLimitsInner
     */
    limit?: number;
    /**
     *
     * @type {number}
     * @memberof SymbolOrderBookTickerResponse1RateLimitsInner
     */
    count?: number;
}
