/* tslint:disable */

/**
 * Binance Mining REST API
 *
 * OpenAPI Specification for the Binance Mining REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AcquiringAlgorithmResponseDataInner
 */
export interface AcquiringAlgorithmResponseDataInner {
    /**
     *
     * @type {string}
     * @memberof AcquiringAlgorithmResponseDataInner
     */
    algoName?: string;
    /**
     *
     * @type {number}
     * @memberof AcquiringAlgorithmResponseDataInner
     */
    algoId?: number;
    /**
     *
     * @type {number}
     * @memberof AcquiringAlgorithmResponseDataInner
     */
    poolIndex?: number;
    /**
     *
     * @type {string}
     * @memberof AcquiringAlgorithmResponseDataInner
     */
    unit?: string;
}
