/* tslint:disable */

/**
 * Binance Public Mining REST API
 *
 * OpenAPI Specification for the Binance Public Mining REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MiningAccountEarningResponseDataAccountProfitsInner
 */
export interface MiningAccountEarningResponseDataAccountProfitsInner {
    /**
     *
     * @type {number}
     * @memberof MiningAccountEarningResponseDataAccountProfitsInner
     */
    time?: number;
    /**
     *
     * @type {string}
     * @memberof MiningAccountEarningResponseDataAccountProfitsInner
     */
    coinName?: string;
    /**
     *
     * @type {number}
     * @memberof MiningAccountEarningResponseDataAccountProfitsInner
     */
    type?: number;
    /**
     *
     * @type {number}
     * @memberof MiningAccountEarningResponseDataAccountProfitsInner
     */
    puid?: number;
    /**
     *
     * @type {string}
     * @memberof MiningAccountEarningResponseDataAccountProfitsInner
     */
    subName?: string;
    /**
     *
     * @type {number}
     * @memberof MiningAccountEarningResponseDataAccountProfitsInner
     */
    amount?: number;
}
