/* tslint:disable */

/**
 * Binance Derivatives Trading Options WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Derivatives Trading Options WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AccountUpdatePInner
 */
export interface AccountUpdatePInner {
    /**
     *
     * @type {string}
     * @memberof AccountUpdatePInner
     */
    s?: string;
    /**
     *
     * @type {string}
     * @memberof AccountUpdatePInner
     */
    c?: string;
    /**
     *
     * @type {string}
     * @memberof AccountUpdatePInner
     */
    r?: string;
    /**
     *
     * @type {string}
     * @memberof AccountUpdatePInner
     */
    p?: string;
    /**
     *
     * @type {string}
     * @memberof AccountUpdatePInner
     */
    a?: string;
}
